# wrangler.toml
name = "helpbase"
compatibility_date = "2024-01-15"
pages_build_output_dir = ".next/static"

[[routes]]
pattern = "helpbase.co/*"
custom_domain = "helpbase.co"

[[routes]]
pattern = "www.helpbase.co/*" 
custom_domain = "www.helpbase.co"

[[routes]]
pattern = "accounts.helpbase.co/*"
custom_domain = "accounts.helpbase.co"