name: Deploy Auth Worker

on:
  push:
    branches: [main, develop]
    paths: ["workers/**", "wrangler.toml"]
  pull_request:
    branches: [main]
    paths: ["workers/**", "wrangler.toml"]
  workflow_dispatch:

jobs:
  deploy-worker:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy workers/auth.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  test-worker:
    name: Test Worker Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Worker Syntax
        run: |
          node -c workers/auth.js
          echo "✅ Worker syntax is valid"
