name: Tests and Validation

on: [push, pull_request]

jobs:
  test:
    name: Run Tests and Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Validate redirects
        run: |
          if [ ! -f "public/_redirects" ]; then
            echo "❌ _redirects file missing"
            exit 1
          fi
          echo "✅ _redirects file exists"
